// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatisTakipSistemi.Data;

#nullable disable

namespace SatisTakipSistemi.Migrations
{
    [DbContext(typeof(SatisTakipSistemiContext))]
    [Migration("20251213161128_Gecis")]
    partial class Gecis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SatisTakipSistemi.Models.SatisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SorumluSatisci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SatisKaydi");
                });
#pragma warning restore 612, 618
        }
    }
}
